# Logfile created on 2014-07-10 14:11:12 by logger.rb/44203
I, [2014-07-10T14:11:12.722745 #16866]  INFO -- : *** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
E, [2014-07-10T14:11:12.722894 #16866] ERROR -- : Must be one of [:method, :headers, :body, :heartbeat] (AMQ::Protocol::FrameTypeError)
/home/yuva/.rvm/gems/ruby-2.1.1/gems/amq-protocol-1.9.2/lib/amq/protocol/frame.rb:64:in `decode_header'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/bunny-1.2.1/lib/bunny/transport.rb:208:in `read_next_frame'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/bunny-1.2.1/lib/bunny/session.rb:923:in `init_connection'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/bunny-1.2.1/lib/bunny/session.rb:254:in `start'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/amqp_daemon.rb:17:in `<top (required)>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/withdraw_audit_ctl:11:in `<main>'
I, [2014-07-10T14:11:12.725350 #16866]  INFO -- : *** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
E, [2014-07-10T14:11:12.725453 #16866] ERROR -- : exception reentered (fatal)

E, [2014-07-10T14:11:12.735438 #16866] ERROR -- : stream closed (IOError)

E, [2014-07-10T14:11:12.735588 #16866] ERROR -- : failed to allocate memory (NoMemoryError)

E, [2014-07-10T14:11:12.735656 #16866] ERROR -- : stack level too deep (SystemStackError)

E, [2014-07-10T14:11:12.745585 #16866] ERROR -- : Value will be available once the pipeline executes. (Redis::FutureNotReady)

E, [2014-07-10T14:11:12.832187 #16866] ERROR -- : no such frame (ArgumentError)
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `frame_binding'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `block (2 levels) in callers'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `loop'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `block in callers'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `open'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `callers'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/better_errors-1.1.0/lib/better_errors/core_ext/exception.rb:9:in `block in <class:Exception>'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/open-uri.rb:36:in `initialize'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/open-uri.rb:36:in `open'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/open-uri.rb:36:in `open'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/logger.rb:592:in `open_logfile'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/logger.rb:549:in `initialize'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/logger.rb:318:in `new'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/logger.rb:318:in `initialize'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:353:in `new'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:353:in `exception_log'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:165:in `block in start_load'
E, [2014-07-10T14:11:12.832798 #16866] ERROR -- : No such file or directory @ rb_sysopen - /home/yuva/Desktop/arvind/peatio/peatio-master/log/peatio:amqp:withdraw_audit.log (Errno::ENOENT)
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/open-uri.rb:36:in `initialize'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/open-uri.rb:36:in `open'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/open-uri.rb:36:in `open'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/logger.rb:592:in `open_logfile'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/logger.rb:549:in `initialize'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/logger.rb:318:in `new'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/logger.rb:318:in `initialize'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:353:in `new'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:353:in `exception_log'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:165:in `block in start_load'
E, [2014-07-10T14:11:12.832910 #16866] ERROR -- : no such frame (ArgumentError)
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `frame_binding'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `block (2 levels) in callers'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `loop'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `block in callers'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `open'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `callers'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/better_errors-1.1.0/lib/better_errors/core_ext/exception.rb:9:in `block in <class:Exception>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/amq-protocol-1.9.2/lib/amq/protocol/frame.rb:64:in `decode_header'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/bunny-1.2.1/lib/bunny/transport.rb:208:in `read_next_frame'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/bunny-1.2.1/lib/bunny/session.rb:923:in `init_connection'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/bunny-1.2.1/lib/bunny/session.rb:254:in `start'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/amqp_daemon.rb:17:in `<top (required)>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/withdraw_audit_ctl:11:in `<main>'
E, [2014-07-10T14:11:12.833019 #16866] ERROR -- : Must be one of [:method, :headers, :body, :heartbeat] (AMQ::Protocol::FrameTypeError)
/home/yuva/.rvm/gems/ruby-2.1.1/gems/amq-protocol-1.9.2/lib/amq/protocol/frame.rb:64:in `decode_header'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/bunny-1.2.1/lib/bunny/transport.rb:208:in `read_next_frame'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/bunny-1.2.1/lib/bunny/session.rb:923:in `init_connection'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/bunny-1.2.1/lib/bunny/session.rb:254:in `start'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/amqp_daemon.rb:17:in `<top (required)>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/withdraw_audit_ctl:11:in `<main>'
I, [2014-07-14T17:53:58.118536 #25326]  INFO -- : *** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
E, [2014-07-14T17:53:58.241444 #25326] ERROR -- : Resource temporarily unavailable - read would block (IO::EAGAINWaitReadable)
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:41:in `read_nonblock'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:41:in `block in read_fully'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:40:in `loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:40:in `read_fully'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/transport.rb:199:in `read_next_frame'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:63:in `run_once'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:33:in `block in run_loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:30:in `loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:30:in `run_loop'
I, [2014-07-14T17:53:58.241607 #25326]  INFO -- : *** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
E, [2014-07-14T17:53:58.241743 #25326] ERROR -- : exception reentered (fatal)

E, [2014-07-14T17:53:58.492534 #25326] ERROR -- : stream closed (IOError)

E, [2014-07-14T17:53:58.492791 #25326] ERROR -- : failed to allocate memory (NoMemoryError)

E, [2014-07-14T17:53:58.492902 #25326] ERROR -- : stack level too deep (SystemStackError)

E, [2014-07-14T17:53:58.513204 #25326] ERROR -- : Value will be available once the pipeline executes. (Redis::FutureNotReady)

E, [2014-07-14T17:53:58.551658 #25326] ERROR -- : Resource temporarily unavailable - read would block (IO::EAGAINWaitReadable)
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:41:in `read_nonblock'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:41:in `block in read_fully'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:40:in `loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:40:in `read_fully'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/transport.rb:199:in `read_next_frame'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/session.rb:923:in `init_connection'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/session.rb:254:in `start'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/amqp_daemon.rb:17:in `<top (required)>'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/withdraw_audit_ctl:11:in `<main>'
E, [2014-07-14T17:53:58.568742 #25326] ERROR -- : no such frame (ArgumentError)
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `frame_binding'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `block (2 levels) in callers'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `block in callers'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `open'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `callers'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/better_errors-1.1.0/lib/better_errors/core_ext/exception.rb:9:in `block in <class:Exception>'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:41:in `read_nonblock'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:41:in `block in read_fully'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:40:in `loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:40:in `read_fully'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/transport.rb:199:in `read_next_frame'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/session.rb:923:in `init_connection'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/session.rb:254:in `start'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/amqp_daemon.rb:17:in `<top (required)>'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/withdraw_audit_ctl:11:in `<main>'
E, [2014-07-14T17:53:58.568987 #25326] ERROR -- : Resource temporarily unavailable - read would block (IO::EAGAINWaitReadable)
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:41:in `read_nonblock'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:41:in `block in read_fully'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:40:in `loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:40:in `read_fully'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/transport.rb:199:in `read_next_frame'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:63:in `run_once'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:33:in `block in run_loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:30:in `loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:30:in `run_loop'
E, [2014-07-14T17:53:58.569124 #25326] ERROR -- : no such frame (ArgumentError)
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `frame_binding'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `block (2 levels) in callers'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `block in callers'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `open'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `callers'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/better_errors-1.1.0/lib/better_errors/core_ext/exception.rb:9:in `block in <class:Exception>'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:41:in `read_nonblock'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:41:in `block in read_fully'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:40:in `loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:40:in `read_fully'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/transport.rb:199:in `read_next_frame'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:63:in `run_once'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:33:in `block in run_loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:30:in `loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:30:in `run_loop'
E, [2014-07-14T17:53:58.569230 #25326] ERROR -- : Resource temporarily unavailable - read would block (IO::EAGAINWaitReadable)
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:41:in `read_nonblock'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:41:in `block in read_fully'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:40:in `loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:40:in `read_fully'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/transport.rb:199:in `read_next_frame'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:63:in `run_once'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:33:in `block in run_loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:30:in `loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:30:in `run_loop'
E, [2014-07-14T17:53:58.569367 #25326] ERROR -- : no such frame (ArgumentError)
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `frame_binding'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `block (2 levels) in callers'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `block in callers'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `open'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `callers'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/better_errors-1.1.0/lib/better_errors/core_ext/exception.rb:9:in `block in <class:Exception>'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:41:in `read_nonblock'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:41:in `block in read_fully'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:40:in `loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:40:in `read_fully'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/transport.rb:199:in `read_next_frame'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:63:in `run_once'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:33:in `block in run_loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:30:in `loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:30:in `run_loop'
E, [2014-07-14T17:53:58.569470 #25326] ERROR -- : Resource temporarily unavailable - read would block (IO::EAGAINWaitReadable)
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:41:in `read_nonblock'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:41:in `block in read_fully'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:40:in `loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:40:in `read_fully'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/transport.rb:199:in `read_next_frame'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:63:in `run_once'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:33:in `block in run_loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:30:in `loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:30:in `run_loop'
E, [2014-07-14T17:53:58.569557 #25326] ERROR -- : no such frame (ArgumentError)
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `frame_binding'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `block (2 levels) in callers'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `block in callers'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `open'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `callers'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/better_errors-1.1.0/lib/better_errors/core_ext/exception.rb:9:in `block in <class:Exception>'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:41:in `read_nonblock'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:41:in `block in read_fully'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:40:in `loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:40:in `read_fully'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/transport.rb:199:in `read_next_frame'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:63:in `run_once'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:33:in `block in run_loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:30:in `loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:30:in `run_loop'
E, [2014-07-14T17:53:58.569890 #25326] ERROR -- : no such frame (ArgumentError)
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `frame_binding'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `block (2 levels) in callers'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `block in callers'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `open'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `callers'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/better_errors-1.1.0/lib/better_errors/core_ext/exception.rb:9:in `block in <class:Exception>'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:55:in `join'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:55:in `block in join'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:55:in `each'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:55:in `join'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/amqp_daemon.rb:80:in `<top (required)>'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/withdraw_audit_ctl:11:in `<main>'
E, [2014-07-14T17:53:58.570013 #25326] ERROR -- : no such frame (ArgumentError)
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `frame_binding'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `block (2 levels) in callers'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `block in callers'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `open'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `callers'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/better_errors-1.1.0/lib/better_errors/core_ext/exception.rb:9:in `block in <class:Exception>'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:94:in `raise'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:94:in `raise'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/session.rb:796:in `maybe_shutdown_reader_loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/session.rb:705:in `clean_up_on_shutdown'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/session.rb:698:in `clean_up_and_fail_on_connection_close!'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/session.rb:533:in `handle_frame'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:81:in `run_once'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:33:in `block in run_loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:30:in `loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:30:in `run_loop'
E, [2014-07-14T17:53:58.570114 #25326] ERROR -- : Bunny::ShutdownSignal (Bunny::ShutdownSignal)
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:94:in `raise'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:94:in `raise'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/session.rb:796:in `maybe_shutdown_reader_loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/session.rb:705:in `clean_up_on_shutdown'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/session.rb:698:in `clean_up_and_fail_on_connection_close!'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/session.rb:533:in `handle_frame'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:81:in `run_once'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:33:in `block in run_loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:30:in `loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:30:in `run_loop'
E, [2014-07-14T17:53:58.570194 #25326] ERROR -- : Connection-level error: CONNECTION_FORCED - broker forced connection closure with reason 'shutdown' (Bunny::ConnectionForced)
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:55:in `join'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:55:in `block in join'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:55:in `each'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:55:in `join'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/amqp_daemon.rb:80:in `<top (required)>'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/withdraw_audit_ctl:11:in `<main>'
E, [2014-07-14T17:53:58.570297 #25326] ERROR -- : no such frame (ArgumentError)
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `frame_binding'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `block (2 levels) in callers'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `block in callers'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `open'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `callers'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/better_errors-1.1.0/lib/better_errors/core_ext/exception.rb:9:in `block in <class:Exception>'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:41:in `read_nonblock'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:41:in `block in read_fully'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:40:in `loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:40:in `read_fully'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/transport.rb:199:in `read_next_frame'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:63:in `run_once'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:33:in `block in run_loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:30:in `loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:30:in `run_loop'
E, [2014-07-14T17:53:58.570392 #25326] ERROR -- : Resource temporarily unavailable - read would block (IO::EAGAINWaitReadable)
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:41:in `read_nonblock'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:41:in `block in read_fully'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:40:in `loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:40:in `read_fully'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/transport.rb:199:in `read_next_frame'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:63:in `run_once'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:33:in `block in run_loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:30:in `loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:30:in `run_loop'
